import Head from "next/head";



export const metadata = {
  title: "Login",
  description: "Generated by create next app",

};
export default function Index() {
  return (
    <>
      <Head>
        <title>New Project</title>
        <meta name="description" content="" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
      </Head>
      {/* Font Size */}
      <div className="login-wrap-bg">



      </div>
     
    </>
  );
}
