'use client'
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { InputNumber } from "primereact/inputnumber";
import { InputText } from "primereact/inputtext";
import { Checkbox } from "primereact/checkbox";
import { useState } from "react";



// export const metadata = {
//   title: "Login",
//   description: "Generated by create next app",

// };
export default function Index() {
  const [checked, setChecked] = useState(false);
  return (
    <>
      {/* <Head>
        <title>New Project</title>
        <meta name="description" content="" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
      </Head> */}
      {/* Font Size */}
      <div className="login-wrap-bg">

      <div className='grid grid-cols-12 xl:grid-cols-2 gap-[20px] 3xl:gap-[1.042vw]  3xl:mx-[1.042vw]'>
                <div className='hidden lg:block col-span-12 lg:col-span-1 xl:col-span-1'>

                  </div>
                  <div className='col-span-12 lg:col-span-10 xl:col-span-1 login'>
                    <div className="bg-[#fff] 3xl:my-[3.385vw] 3xl:mx-[5.469vw] 3xl:py-[3.125vw] 3xl:px-[6.25vw] lg:my-[65px] lg:mx-[80px] lg:px-[80px] lg:py-[40px] border-2 border-[#A93238] rounded-xl">
                    
                      <Image className='' height={75} width={250} src={"/assets/images/logo.png"} alt={"logo"}/>

                      <div className="3xl:mt-[3.375vw] lg:mt-[84px] mt-[84px]">
                      
                        <h2 className="text-[#3A3A3C] xl:text-[28px] text-[22px] 3xl:text-[1.875vw] font-semibold">Login</h2>
                        <p className="text-[#3A3A3C] xl:text-[16px]  lg:text-[16px] text-[18px] 3xl:text-[0.938vw] font-normal">Please provide your credentials to proceed!</p>

                        <div className="3xl:mt-[2.083vw] lg:mt-[40px] mt-[40px]">
                        <Link href='' className="border border-[#E8F0F3] rounded-lg bg-[#fff] shadow-lg w-full text-[#101828] xl:text-[16px] text-[16px] 3xl:text-[0.833vw] 
                        3xl:py-[0.633vw] lg:py-[8px] py-[8px] flex font-semibold justify-center gap-2"> <Image className='' height={20} width={20} src={"/assets/images/google_log_icon.svg"} alt={"logo"}/> Sign in with Google</Link>
                        </div>
                        <div className="3xl:my-[2.083vw] lg:my-[40px] my-[40px]">
                           <Image className='' height={24} width={498} src={"/assets/images/signin.png"} alt={"logo"}/> 
                        </div>

                        <form>
                          <div className="custInputBox 3xl:mb-[1.563vw] lg:mb-[25px] mb-[20px]">
                            <label className="text-[#3A3A3C] xl:text-[14px] text-[14px] 3xl:text-[0.729vw] font-medium leading-8">Email</label>
                            <InputText  placeholder="olivia@untitledui.com" className="w-full" />
                          </div>
                          <div className="custInputBox 3xl:mb-[1.563vw] lg:mb-[30px] mb-[30px]">
                            <label className="text-[#3A3A3C] xl:text-[14px] text-[14px] 3xl:text-[0.729vw] font-medium leading-8">Password</label>
                            <InputText  placeholder="*******" className="w-full" />
                          </div>
                        <div className="flex justify-between 3xl:mb-[1.719vw] lg:mb-[33px] mb-[33px]">
                          <div>
                              <Checkbox onChange={e => setChecked(e.checked)} checked={checked}></Checkbox>
                              <label htmlFor="" className="ml-2 text-[#3A3A3C] xl:text-[16px] text-[16px] 3xl:text-[0.833vw] font-medium">Remember Me</label>
                          </div>
                          <div >
                            
                              <Link href='' className="text-[#4C80E4] xl:text-[16px] text-[16px] 3xl:text-[0.833vw] font-medium">Forget Password?</Link>
                          </div>

                          </div>
                          <Link href='' className="bg-[#A93238] border text-[#fff] border-[#E8F0F3] rounded-lg w-full xl:text-[16px] text-[16px] 3xl:text-[0.833vw] 
                        3xl:py-[0.633vw] lg:py-[8px] py-[8px] flex font-medium justify-center gap-2">Login</Link>

                        </form>
                        
                      </div>
                    </div>
                  </div>
        </div>


      </div>
     
    </>
  );
}
